_base_: experiment_dinov3.yaml

wandb:
  run_name: colormnet_dinov3_finetune
  job_type: training-finetune

training:
  exp_id: colormnet_dinov3_finetune
  finetune_only: true
  load_network_artifact: colormnet_dinov3_s2-model:v0
  load_network_file: colormnet_dinov3_s2_best.pth
  stage2:
    iterations: 0
    finetune: 2000
    lr: 0.00001
